language: node_js
node_js:
- 10
cache:
  yarn: true
  directories:
  - node_modules
stages:
- name: test
  if: branch != master
- name: deploy
  if: branch = master
before_install:
- openssl aes-256-cbc -K $encrypted_62d329f44213_key -iv $encrypted_62d329f44213_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa

- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.8.0
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn install --no-lockfile
jobs:
  include:
  - stage: test
    script: yarn test
  - stage: deploy
    script: yarn deploy
